name: medical
description: ""


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  lottie: ^3.1.3
  flutter_svg: ^2.0.16
  firebase_auth: ^5.3.3
  get: ^4.6.6
  cloud_firestore: ^5.5.0
  mask_text_input_formatter: ^2.9.0
  iconsax: ^0.0.8
  intl: ^0.19.0
  url_launcher: ^6.3.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  shared_preferences: ^2.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/languages/
    - assets/lottie/
    - assets/images/
    - assets/on_boarding/